# Generated file, do not modify by hand
# Generated by 'rbe_ubuntu1604_java8_autogen' rbe_autoconfig rule
"""Definitions to be used in rbe_repo attr of an rbe_autoconf rule  """
toolchain_config_spec0 = struct(config_repos = [], create_cc_configs = True, create_java_configs = True, env = {}, java_home = "/usr/lib/jvm/java-8-openjdk-amd64", name = "default_toolchain_config_spec_name")
_TOOLCHAIN_CONFIG_SPECS = [toolchain_config_spec0]
_BAZEL_TO_CONFIG_SPEC_NAMES = {"2.1.0": ["default_toolchain_config_spec_name"]}
LATEST = "sha256:6eefc9d50d92a15c9c52701f89c34a5d778829357fee0c6e46efa5dec1152b0a"
CONTAINER_TO_CONFIG_SPEC_NAMES = {"sha256:6eefc9d50d92a15c9c52701f89c34a5d778829357fee0c6e46efa5dec1152b0a": ["default_toolchain_config_spec_name"]}
_DEFAULT_TOOLCHAIN_CONFIG_SPEC = toolchain_config_spec0
TOOLCHAIN_CONFIG_AUTOGEN_SPEC = struct(
        bazel_to_config_spec_names_map = _BAZEL_TO_CONFIG_SPEC_NAMES,
        container_to_config_spec_names_map = CONTAINER_TO_CONFIG_SPEC_NAMES,
        default_toolchain_config_spec = _DEFAULT_TOOLCHAIN_CONFIG_SPEC,
        latest_container = LATEST,
        toolchain_config_specs = _TOOLCHAIN_CONFIG_SPECS,
    )